name: dependent jobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        run: echo "checkout"
      - name: Build the Code
        run: echo "build"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy the Build
        run: echo "deploy"
    
